# Generated by Django 5.0.2 on 2024-02-29 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(choices=[('Chest', 'Chest'), ('Shoulders', 'Shoulders'), ('Bicep', 'Bicep'), ('Triceps', 'Triceps'), ('Legs', 'Legs'), ('Back', 'Back'), ('Glutes', 'Glutes'), ('Abs', 'Abs'), ('Calves', 'Calves')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=50)),
                ('body_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programbuilder.bodypart')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programbuilder.day')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('order', models.PositiveBigIntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programbuilder.exercise')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programbuilder.programday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('days', models.ManyToManyField(through='programbuilder.ProgramDay', to='programbuilder.day')),
            ],
        ),
        migrations.AddField(
            model_name='programday',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programbuilder.workoutprogram'),
        ),
        migrations.AlterUniqueTogether(
            name='programday',
            unique_together={('program', 'order')},
        ),
    ]
