# Generated by Django 5.0.2 on 2024-03-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programbuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseInProgram',
            new_name='ExerciseInDay',
        ),
    ]
