# Generated by Django 5.0.2 on 2024-03-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programbuilder', '0002_rename_exerciseinprogram_exerciseinday'),
    ]

    operations = [
        migrations.AddField(
            model_name='programday',
            name='rest_day',
            field=models.BooleanField(default=False),
        ),
    ]
