# Generated by Django 5.0.2 on 2024-03-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programbuilder', '0003_programday_rest_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programday',
            name='rest_day',
            field=models.BooleanField(),
        ),
    ]
