# Generated by Django 5.0.2 on 2024-03-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programbuilder', '0006_rename_program_programday_program_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutprogram',
            name='days',
        ),
        migrations.AlterUniqueTogether(
            name='programday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programday',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='program_days',
            field=models.ManyToManyField(to='programbuilder.programday'),
        ),
        migrations.RemoveField(
            model_name='programday',
            name='day',
        ),
        migrations.RemoveField(
            model_name='programday',
            name='order',
        ),
        migrations.RemoveField(
            model_name='programday',
            name='program_day',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
