# Generated by Django 5.0.2 on 2024-03-06 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programbuilder', '0007_remove_workoutprogram_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutprogram',
            name='program_days',
        ),
        migrations.AddField(
            model_name='programday',
            name='workout_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programbuilder.workoutprogram'),
        ),
    ]
