# Generated by Django 5.0.2 on 2024-03-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programbuilder', '0008_remove_workoutprogram_program_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseinday',
            options={},
        ),
        migrations.RemoveField(
            model_name='exerciseinday',
            name='order',
        ),
    ]
