# Generated by Django 5.0.2 on 2024-03-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programbuilder', '0009_alter_exerciseinday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programday',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20),
        ),
    ]
