# Generated by Django 5.0.2 on 2024-03-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programbuilder', '0010_workoutprogram_is_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutprogram',
            old_name='is_template',
            new_name='template',
        ),
    ]
