# Generated by Django 5.0.2 on 2024-03-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programbuilder', '0011_rename_is_template_workoutprogram_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
